name: Package

on:
  push:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 18.0.2
          distribution: 'zulu'
          java-package: 'jdk+fx'
          cache: 'maven'

      - name: Build native installer
        run: mvn clean install
          
      - name: Upload native installer
        uses: actions/upload-artifact@v4
        with:
          name: J3-${{ runner.os }}
          path: |
            ./target/*.msi
            ./target/*.dmg
            ./target/*.deb
            
      - name: Create platform-independent bundle
        if: runner.os == 'Linux'
        run: |
          pushd target
          mkdir J3
          cp -r lib/ J3
          cp -r runtime/ J3
          cp -r ../data J3
          cp -r ../animations J3
          cp ../src/packaging/j3.bat J3
          cp ../src/packaging/j3 J3
          chmod +x J3/j3
          
      - name: Upload platform-independent bundle
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: J3
          path: |
            ./target/J3
