name: Package

on:
  push:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 18.0.2
          distribution: 'zulu'
          java-package: 'jdk+fx'
          cache: 'maven'

      - name: Maven build
        run: mvn clean install
          
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: J3-${{ runner.os }}
          path: |
            ./target/*.msi
            ./target/*.dmg
            ./target/*.deb
